MODEL:
    NUM_CLASSES: 4
    BACKBONE:
        NAME: 'resnet152'
        PRETRAINED: True
        OUT_CHANNELS: [512, 1024, 2048, 1024, 1024, 512] # resnet152
        #OUT_CHANNELS: [128, 256, 512, 512, 256, 256] # resnet18
        #OUT_CHANNELS: [512, 1024, 512, 512, 256, 256] # model from assignment 4
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "/work/datasets"
EVAL_STEP: 2000 # Evaluate dataset every eval_step, disabled when eval_step < 0
MODEL_SAVE_STEP: 2000 # Save checkpoint every save_step
