MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet18'
        PRETRAINED: True
        #OUT_CHANNELS: [512, 1024, 2048, 1024, 1024, 512] # resnet152
        OUT_CHANNELS: [128, 256, 512, 1024, 512, 512] # resnet18
        #OUT_CHANNELS: [512, 1024, 512, 512, 256, 256] # model from assignment 4
        INPUT_CHANNELS: 3
    PRIORS:
        #FEATURE_MAPS: [[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
        #FEATURE_MAPS: [[75, 75], [38, 38], [19, 19], [10, 10], [5, 5], [3, 3]] # Image_size = [600, 600]
        FEATURE_MAPS: [[75, 75], [38, 38], [19, 19], [9, 9], [4, 4], [2, 2]] # Image_size = [600, 600] and maxpool instead of conv stride=2
        #STRIDES: [[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
        STRIDES: [[8, 8], [16, 16], [32, 32], [67, 67], [150, 150], [300, 300]]
        #MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        #MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        MIN_SIZES: [[60, 60], [120, 120], [222, 222], [324, 324], [426, 426], [528, 528]]  # Double image size
        MAX_SIZES: [[120, 120], [222, 222], [324, 324], [426, 426], [528, 528], [630, 630]]  # Double image size
INPUT:
    IMAGE_SIZE: [600, 600]

DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-4
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "/work/datasets"
EVAL_STEP: 5000 # Evaluate dataset every eval_step, disabled when eval_step < 0
MODEL_SAVE_STEP: 5000 # Save checkpoint every save_step
